FROM golang:1.24-alpine

WORKDIR /app

RUN apk add --no-cache git

COPY go.mod go.sum ./
RUN go mod tidy
RUN go mod download

COPY . .

RUN go install github.com/air-verse/air@latest

ENV PATH="/root/go/bin:${PATH}"

EXPOSE 8000

CMD ["air"]